# Generated by Django 3.1 on 2020-12-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens_amount',
            field=models.IntegerField(default=0, verbose_name='Tokens Amount of User'),
        ),
    ]
