# Generated by Django 3.1 on 2020-12-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_tokens_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fiat_currency',
            field=models.CharField(choices=[('NO_CURRENCY', '-'), ('EURO', 'EUR'), ('US_DOLLAR', 'USD'), ('BRITISH_POUND', 'GBP')], default='EURO', max_length=50, verbose_name='Fiat Currency'),
        ),
    ]
